from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')+Glob('../src/*.cpp')
CPPPATH = [cwd]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
